import type { Metadata } from "next";
import "./globals.css";
import { geistMono, geistSans } from "../utils/fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="root">{children}</div>
			</body>
		</html>
	);
}
